### ISSUE TITLE
{bslib} cards fail to appear in deployed Shinylive app

### ISSUE THREAD

**Issue by matt-dray** [matt-dray/cran-deadlines#1]
The cards of information appear when the app is run locally, but not when you view via `httpuv::runStaticServer("docs")` or [the deployed Shinylive app](https://matt-dray.github.io/cran-deadlines/).

**Comment by rpodcast** [comment]
I did a quick check in the developer console and it looks like the shinylive process is not picking up the `packages.rds` file:

![image](https://github.com/matt-dray/cran-deadlines/assets/1043111/b62535f2-b21f-4281-839f-65a265c073ce)

I've been working extensively on a web-assembly version of a Shiny application throughout the year. If I get time I will investigate this and see if there's a solution. You app is fantastic and fulfills a huge need in the community!

**Comment by matt-dray** [comment]
I appreciate that Eric, thank you for taking a look. Luckily I had one spare shinyapps.io spot for now!

You may already have seen [Hadley's rendition](https://hadley.github.io/cran-deadlines/) of this kind of tool, which looks very useful.

**Comment by rpodcast** [comment]
> You may already have seen [Hadley's rendition](https://hadley.github.io/cran-deadlines/) of this kind of tool, which looks very useful.

I was not aware of Hadley's version, and very much agree it is quite useful. I see that it's a quarto doc re-published twice a day with GH actions. Going to fork your repo now and see what I can find out!
