### ISSUE TITLE
Open links in a new tab

### ISSUE THREAD

**Issue by simon-smart88** [matt-dray/cran-deadlines#7]
Currently if you click on a link it opens in the same tab which means if you navigate back you have to reload the app. You can force links to open in new tabs by adding `target="_blank"` into your `htmltools::a()` functions e.g.:

```
htmltools::a(
          href = paste0(
            "https://cran.r-project.org/web/checks/check_results_",
            pkg$Package,
            ".html"
          ),
         target = "_blank",
          "Issues"
        )
```

**Comment by matt-dray** [comment]
That's a very good idea, thank you. Just merged in a fix for this.
